[package]
name = "gtk4-layer-shell-sys"
version = "0.1.1"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
license = "MIT"
description = "Unsave gir-generated FFI bindings for gtk4-layer-shell"
repository = "https://github.com/pentamassiv/gtk4-layer-shell-gir/tree/main/gtk4-layer-shell-sys"
documentation = "https://docs.rs/gtk4-layer-shell-sys/"
keywords = ["gtk4", "gtk4-layer-shell", "wayland", "FFI", "unsafe"]
categories = ["external-ffi-bindings", "gui"]
edition = "2021"
build = "build.rs"

[package.metadata.system-deps.gtk4_layer_shell_0]
name = "gtk4-layer-shell-0"
version = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "gtk4_layer_shell_sys"

[dependencies]
libc = "0.2"

[dependencies.glib]
package = "glib-sys"
version = "0.18"

[dependencies.gdk]
package = "gdk4-sys"
version = "0.7"

[dependencies.gtk]
package = "gtk4-sys"
version = "0.7"

[build-dependencies]
system-deps = "6"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
