name: "Build x86"

permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: rustfmt, clippy
      - name: Update subtrees
        run: |
          git subtree pull --prefix gir https://github.com/gtk-rs/gir.git master --squash
          git subtree pull --prefix gir-files https://github.com/gtk-rs/gir-files.git master --squash
          
      - name: Export environment variables
        run: |
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          export LD_LIBRARY_PATH=/usr/local/lib
      - uses: ./.github/actions/build_test_commit
